name: v5-website
on:
  push:
    branches: [v5-website]

jobs:
  website:
    if: github.repository == 'remix-run/react-router'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test

      - name: Deploy
        run: bash scripts/deploy-website.sh "${{ secrets.WEBSITE_DEPLOY_TOKEN }}"
